/**
 * Core domain types for inventory management.
 */

/** Stock availability status, derived from quantity and reorder threshold. */
export type StockStatus = 'OUT_OF_STOCK' | 'LOW_STOCK' | 'IN_STOCK'

/** A single inventory item available for sale. */
export interface Product {
  id: string
  name: string
  sku: string
  quantity: number
  minThreshold: number
  purchasePrice: number
  sellingPrice: number
  category: string
  /** Optional display unit for quantities (e.g. "kg", "L", "pcs"). */
  unit?: string
}

/** Payload for creating a new product (id is generated by the store). */
export type NewProduct = Omit<Product, 'id'>

/** Fields that can be edited on an existing product. */
export type ProductUpdate = Partial<NewProduct>
