/**
 * Core domain types for inventory management.
 */

/** Stock availability status, derived from quantity and reorder threshold. */
export type StockStatus = 'OUT_OF_STOCK' | 'LOW_STOCK' | 'IN_STOCK'

/** Common retail units used by the POS in Arabic. */
export type ProductUnit = 'علبة' | 'كرتونة'

/** A single inventory item available for sale. */
export interface Product {
  id: string
  name: string
  sku: string
  quantity: number
  minThreshold: number
  purchasePrice: number
  sellingPrice: number
  category: string
  /** Unit used when counting and selling the product. */
  unit?: string
  /** Number of boxes contained in one carton, when the unit is carton. */
  unitsPerCarton?: number
}

/** Payload for creating a new product (id is generated by the store). */
export type NewProduct = Omit<Product, 'id'>

/** Fields that can be edited on an existing product. */
export type ProductUpdate = Partial<NewProduct>
