/**
 * Core domain types for inventory management.
 */

/** Stock availability status, derived from quantity and reorder threshold. */
export type StockStatus = 'OUT_OF_STOCK' | 'LOW_STOCK' | 'IN_STOCK'

/**
 * Retail units used by the POS. Stored as stable data values (see
 * `src/lib/product-unit.ts`), labelled through i18n.
 */
export type ProductUnit = 'قطعة' | 'علبة' | 'كرتونة'

/** A single inventory item available for sale. */
export interface Product {
  id: string
  name: string
  sku: string
  /** Machine-readable barcode (EAN-13, UPC-A, Code 128, ...). Optional — not
   * every product ships with a pre-printed barcode. */
  barcode?: string
  quantity: number
  minThreshold: number
  purchasePrice: number
  sellingPrice: number
  category: string
  /** Unit used when counting and selling the product. */
  unit?: string
  /** Number of boxes contained in one carton, when the unit is carton. */
  unitsPerCarton?: number
}

/** Payload for creating a new product (id is generated by the store). */
export type NewProduct = Omit<Product, 'id'>

/** Fields that can be edited on an existing product. */
export type ProductUpdate = Partial<NewProduct>

/** Direction of a recorded stock movement. */
export type StockMovementType = 'IN'

/**
 * An audit-log entry recorded whenever stock levels change outside a sale
 * (e.g. a purchase invoice / shipment received). Stock-out movements from
 * checkouts are recorded atomically inside the sale transaction instead.
 */
export interface StockTransaction {
  id: string
  productId: string
  /** `IN` for receipts / purchase invoices. */
  type: StockMovementType
  /** Quantity moved (always a positive magnitude for `IN`). */
  quantity: number
  /** Stock level immediately before the movement was applied. */
  previousQuantity: number
  /** Stock level immediately after the movement was applied. */
  newQuantity: number
  /** New purchase cost attached to the product, when provided. */
  costPrice?: number
  /** Username of the account that performed the movement. */
  userId: string
  /** ISO timestamp at which the movement was committed. */
  createdAt: string
}
